<?php

namespace AppBundle\Repository;

/**
 * StressManifestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StressManifestationRepository extends \Doctrine\ORM\EntityRepository
{
}
