<?php

namespace AppBundle\Repository;

/**
 * StressSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StressSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
